---
repos:
  - repo: local
    hooks:
      - id: black
        name: Style check (black)
        entry: black
        language: system
        types:
          - python
        args: ["--line-length", "200"]
      - id: isort
        name: Style check (isort)
        entry: isort
        language: system
        types:
          - python
      - id: flake8
        name: Static analysis (flake8)
        entry: flake8
        language: system
        types:
          - python
      - id: mypy
        name: Static analysis (mypy)
        entry: mypy
        language: system
        types:
          - python
        files: .*\.py
