on: [push]

jobs:
  build_releases:
    name: Release builder
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
        python: ['3.8.8']

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          architecture: 'x64'

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Set PYTHONPATH
        shell: bash
        run: |
          export PYTHONPATH="${GITHUB_WORKSPACE}/src"
          echo "Current PYTHONPATH: $PYTHONPATH"
          ls "${GITHUB_WORKSPACE}/src"
          python -c "import sys;print(sys.path)"
          python -c "import insights;print(insights)"
          echo "PYTHONPATH=${PYTHONPATH}" >> $GITHUB_ENV

      - name: Check PYTHONPATH
        shell: bash
        run: |
          python -c "import insights;print(insights)"

      - name: Build release(s)
        uses: MissionBio/actions@v0.1.3
        with:
          source_path: .
          build_path: build
          electron_path: mosaic-streamlit
        env:
          MOSAIC_STREAMLIT_GUI_RUNNING: true
          PYTHONPATH: ${{ env.PYTHONPATH }}

      - uses: actions/upload-artifact@v2
        with:
          name: tapestri-insights-v4-${{ env.PRODUCT_OS_AND_VERSION }}.zip
          path: ${{ github.workspace }}/release.zip
          if-no-files-found: ignore
        if: ${{ env.SYSTEM_NAME == 'linux' }}

      - run: mv release.dmg tapestri-insights-v4-${{ env.PRODUCT_OS_AND_VERSION }}.dmg
        shell: bash
        if: ${{ env.SYSTEM_NAME == 'macos' }}

      - run: mv release.exe tapestri-insights-v4-${{ env.PRODUCT_OS_AND_VERSION }}.exe
        shell: bash
        if: ${{ env.SYSTEM_NAME == 'windows' }}

      - uses: actions/upload-artifact@v2
        with:
          name: tapestri-insights-v4-${{ env.PRODUCT_OS_AND_VERSION }}.dmg
          path: ${{ github.workspace }}/tapestri-insights-v4-${{ env.PRODUCT_OS_AND_VERSION }}.dmg
          if-no-files-found: ignore
        if: ${{ env.SYSTEM_NAME == 'macos' }}

      - uses: actions/upload-artifact@v2
        with:
          name: tapestri-insights-v4-${{ env.PRODUCT_OS_AND_VERSION }}.exe
          path: ${{ github.workspace }}/tapestri-insights-v4-${{ env.PRODUCT_OS_AND_VERSION }}.exe
          if-no-files-found: ignore
        if: ${{ env.SYSTEM_NAME == 'windows' }}
